### ISSUE TITLE
会考虑给单个URL加开关吗？

### ISSUE THREAD

**Issue by ChauMing** [YGYOOO/ajax-interceptor#7]
![image](https://user-images.githubusercontent.com/10388989/68107566-3a14f880-ff20-11e9-9180-6e642b10c455.png)
类似这样

**Comment by YGYOOO** [comment]
可以考虑，有时间我看下~

**Comment by YGYOOO** [comment]
刚发布了0.7版本支持单个URL开关，正在审核中，过几天应该能审核过并自动更新

**Comment by ChauMing** [comment]
> 刚发布了0.7版本支持单个URL开关，正在审核中，过几天应该能审核过并自动更新

感谢支持

**Comment by Carson1997** [comment]
拦截后，怎么关闭拦截

**Comment by YGYOOO** [comment]
> 拦截后，怎么关闭拦截

关闭开关就行了呀

**Comment by Carson1997** [comment]
可以加你qq吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YGY"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 中午12:02
收件人: "YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 
抄送: "Three mins Heat"<786952046@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7)



 
拦截后，怎么关闭拦截
  
关闭开关就行了呀

**Comment by YGYOOO** [comment]
> 可以加你qq吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YGY"<notifications@github.com&gt;; 发送时间: 2020年3月3日(星期二) 中午12:02 收件人: "YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 抄送: "Three mins Heat"<786952046@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7) 拦截后，怎么关闭拦截 关闭开关就行了呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

594487125 不过白天期间我不上qq

**Comment by Carson1997** [comment]
我知道那个开关，我的情况是我打开开关之后，拦截数据可以拿到，但是页面上的数据被屏蔽显示不出来，只能关了再刷新页面才行





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YGY"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月3日(星期二) 中午12:02
收件人:&nbsp;"YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;;
抄送:&nbsp;"Three mins Heat"<786952046@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7)



 
拦截后，怎么关闭拦截
  
关闭开关就行了呀

**Comment by YGYOOO** [comment]
> 我知道那个开关，我的情况是我打开开关之后，拦截数据可以拿到，但是页面上的数据被屏蔽显示不出来，只能关了再刷新页面才行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"YGY"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月3日(星期二) 中午12:02 收件人:&nbsp;"YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 抄送:&nbsp;"Three mins Heat"<786952046@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7) 拦截后，怎么关闭拦截 关闭开关就行了呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

当然呀，关掉开关后得重新请求数据才行呀，请求是由你页面上的代码发起的，开关只影响发起请求后的结果

**Comment by Carson1997** [comment]
拦截前有数据显示





拦截后数据就不显示








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YGY"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 中午12:05
收件人: "YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 
抄送: "Three mins Heat"<786952046@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7)



 
可以加你qq吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YGY"<notifications@github.com&gt;; 发送时间: 2020年3月3日(星期二) 中午12:02 收件人: "YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 抄送: "Three mins Heat"<786952046@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7) 拦截后，怎么关闭拦截 关闭开关就行了呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
594487125 不过白天期间我不上qq

**Comment by Carson1997** [comment]
可不可以做到:我拦截数据后不影响页面数据的显示，我记得之前是可以截取数据后自己修改，但我不知道怎么代码逻辑那里如何做到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YGY"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 中午12:15
收件人: "YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 
抄送: "Three mins Heat"<786952046@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7)



 
我知道那个开关，我的情况是我打开开关之后，拦截数据可以拿到，但是页面上的数据被屏蔽显示不出来，只能关了再刷新页面才行
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"YGY"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月3日(星期二) 中午12:02 收件人:&nbsp;"YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 抄送:&nbsp;"Three mins Heat"<786952046@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7) 拦截后，怎么关闭拦截 关闭开关就行了呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
当然呀，关掉开关后得重新请求数据才行呀，请求是由你页面上的代码发起的，开关只影响发起请求后的结果

**Comment by YGYOOO** [comment]
> 可不可以做到:我拦截数据后不影响页面数据的显示，我记得之前是可以截取数据后自己修改，但我不知道怎么代码逻辑那里如何做到
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YGY"<notifications@github.com&gt;; 发送时间: 2020年3月3日(星期二) 中午12:15 收件人: "YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 抄送: "Three mins Heat"<786952046@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7) 我知道那个开关，我的情况是我打开开关之后，拦截数据可以拿到，但是页面上的数据被屏蔽显示不出来，只能关了再刷新页面才行 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"YGY"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月3日(星期二) 中午12:02 收件人:&nbsp;"YGYOOO/ajax-interceptor"<ajax-interceptor@noreply.github.com&gt;; 抄送:&nbsp;"Three mins Heat"<786952046@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [YGYOOO/ajax-interceptor] 会考虑给单个URL加开关吗？ (#7) 拦截后，怎么关闭拦截 关闭开关就行了呀 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 当然呀，关掉开关后得重新请求数据才行呀，请求是由你页面上的代码发起的，开关只影响发起请求后的结果 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

现在拦截后可以修改成任意值啊，然后你刷新页面重新触发一遍请求就可以了
